### GET STUDENT
GET http://localhost:9090/student?id=4
Accept: application/json

### GET ALL STUDENTS
GET http://localhost:9090/students
Accept: application/json

### POST STUDENT
POST http://localhost:9090/students/create
Content-Type: application/json
Accept: application/json

{
  "identifier": "2023113920",
  "name": "sam3",
  "email": "sam21@gmail.com",
  "semester": 7,
  "created_at": "2020-04-06T07:04:05Z",
  "updated_at": "2020-04-06T07:04:05Z"
}

### UPDATE STUDENT
PUT http://localhost:9090/students/update
Content-Type: application/json
Accept: application/json

{
  "id": 10,
  "identifier": "3023113820",
  "name": "sam3up",
  "email": "sam21up@gmail.com",
  "semester": 5,
  "created_at": "2021-04-06T08:01:26Z",
  "updated_at": "2021-04-06T08:01:26Z"
}

### DELETE STUDENT
DELETE http://localhost:9090/students/delete?id=9
Accept: application/json

{
  "id": 9,
  "identifier": "3023113820",
  "name": "sam3up",
  "email": "sam21up@gmail.com",
  "semester": 5,
  "created_at": "2021-04-06T08:01:26Z",
  "updated_at": "2021-04-06T08:01:26Z"
}